### ISSUE TITLE
New environment not syncing

### ISSUE THREAD

**Issue by devnill** [Apogaea/voldb#86]
I'm trying to set up a new environment but have hit a snag. I followed the steps up to where you run `$ ./manage.py syncdb` but I'm getting the following error:

```shell
(voldb)devnill@desknill:~/work/voldb$ ./manage.py syncdb/home/devnill/Envs/voldb/local/lib/python2.7/site-packages/dotenv.py:13: UserWarning: can't read ./.env - it doesn't exist.
  warnings.warn("can't read %s - it doesn't exist." % dotenv_path)
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/devnill/Envs/voldb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/devnill/Envs/voldb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/devnill/Envs/voldb/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/home/devnill/Envs/voldb/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/devnill/Envs/voldb/local/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'volunteer.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named excavator
(voldb)devnill@desknill:~/work/voldb$ 
```

Wat do?

**Comment by pipermerriam** [comment]
`pip install -r requirements.txt`

**Comment by excalq** [comment]
I think there is an issue specific to the `client` branch, in which 
`dotenv.load_dotenv(os.path.join(PROJECT_PATH, ".env"))` and
`os.environ.setdefault("DJANGO_SETTINGS_MODULE", "volunteer.settings")` are getting hung up on something.

**Comment by pipermerriam** [comment]
Can you send me the full error output?

**Comment by excalq** [comment]
With ./manage.py as is in the client branch:
```
/Users/arthur/Hacking/Apogaea/voldb/env/lib/python2.7/site-packages/dotenv.py:13: UserWarning: can't read ./.env - it doesn't exist.
  warnings.warn("can't read %s - it doesn't exist." % dotenv_path)
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```
Commenting out the `.env` load still gives an error when loading `volunteer.settings` due to "No module named django.core.management"

**Comment by excalq** [comment]
Currently working with @devnill and @Zaskoda to get `client` and `django_integration` up and running. We're blocked on `./manage.py syncdb` with this error:
```
/Users/arthur/Hacking/Apogaea/voldb/env/lib/python2.7/site-packages/dotenv.py:13: UserWarning: can't read ./.env - it doesn't exist.
  warnings.warn("can't read %s - it doesn't exist." % dotenv_path)
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/arthur/Hacking/Apogaea/voldb/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/arthur/Hacking/Apogaea/voldb/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/Users/arthur/Hacking/Apogaea/voldb/env/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/Users/arthur/Hacking/Apogaea/voldb/env/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/arthur/Hacking/Apogaea/voldb/env/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'volunteer.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named excavator
```

We're trying to fix requirements/env issues at the cause of this.

**Comment by pipermerriam** [comment]
Looks like a missing python requirement. I just PR'd a fix in for this to
the main upstream client branch.  The missing requirement is
`python-dotenv`.  If you `pip install -r requirements.txt` after pulling
those changes down, things should start working.


Piper

**Comment by excalq** [comment]
Badass! That worked great. Thanks @pipermerriam
